artifact_uri: ./mlruns/0/c652b09596da446a8543aac2f96b6bb2/artifacts
end_time: 1649862740976
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: c652b09596da446a8543aac2f96b6bb2
run_uuid: c652b09596da446a8543aac2f96b6bb2
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862740947
status: 3
tags: []
user_id: lukaslange
