artifact_uri: ./mlruns/0/42a5ec701de248e3b9903bc3df1f7117/artifacts
end_time: 1649862932499
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 42a5ec701de248e3b9903bc3df1f7117
run_uuid: 42a5ec701de248e3b9903bc3df1f7117
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862932469
status: 3
tags: []
user_id: lukaslange
