artifact_uri: ./mlruns/0/045468be926340ec95fc0bcee4c3bdb6/artifacts
end_time: 1649938963024
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 045468be926340ec95fc0bcee4c3bdb6
run_uuid: 045468be926340ec95fc0bcee4c3bdb6
source_name: ''
source_type: 4
source_version: ''
start_time: 1649938957186
status: 3
tags: []
user_id: lukaslange
