artifact_uri: ./mlruns/0/237baa4a4e834b57a474d22531fab3af/artifacts
end_time: 1649859797172
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 237baa4a4e834b57a474d22531fab3af
run_uuid: 237baa4a4e834b57a474d22531fab3af
source_name: ''
source_type: 4
source_version: ''
start_time: 1649859797131
status: 3
tags: []
user_id: lukaslange
