artifact_uri: ./mlruns/0/fc795619e0624d5ca0aa4f3fa530f756/artifacts
end_time: 1649865877353
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: fc795619e0624d5ca0aa4f3fa530f756
run_uuid: fc795619e0624d5ca0aa4f3fa530f756
source_name: ''
source_type: 4
source_version: ''
start_time: 1649865877312
status: 3
tags: []
user_id: lukaslange
