artifact_uri: ./mlruns/0/eba45e9c30b842189404d79e6e40a1fa/artifacts
end_time: 1649938600792
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: eba45e9c30b842189404d79e6e40a1fa
run_uuid: eba45e9c30b842189404d79e6e40a1fa
source_name: ''
source_type: 4
source_version: ''
start_time: 1649938596551
status: 4
tags: []
user_id: lukaslange
