artifact_uri: ./mlruns/0/75d778eb65584b7baf018b7da6fddbc0/artifacts
end_time: 1649867110449
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 75d778eb65584b7baf018b7da6fddbc0
run_uuid: 75d778eb65584b7baf018b7da6fddbc0
source_name: ''
source_type: 4
source_version: ''
start_time: 1649867110420
status: 3
tags: []
user_id: lukaslange
