artifact_uri: ./mlruns/0/e135ff18a2ce458a878267ac1e55b1e6/artifacts
end_time: 1649866815009
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: e135ff18a2ce458a878267ac1e55b1e6
run_uuid: e135ff18a2ce458a878267ac1e55b1e6
source_name: ''
source_type: 4
source_version: ''
start_time: 1649866814972
status: 4
tags: []
user_id: lukaslange
