artifact_uri: ./mlruns/0/8d557c12b495465d8ee9145ae1eeac2f/artifacts
end_time: 1649865877306
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 8d557c12b495465d8ee9145ae1eeac2f
run_uuid: 8d557c12b495465d8ee9145ae1eeac2f
source_name: ''
source_type: 4
source_version: ''
start_time: 1649865877266
status: 3
tags: []
user_id: lukaslange
