artifact_uri: ./mlruns/0/4d672ed9692e4aef8dbe36c44a6405c9/artifacts
end_time: 1649862932283
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 4d672ed9692e4aef8dbe36c44a6405c9
run_uuid: 4d672ed9692e4aef8dbe36c44a6405c9
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862932253
status: 3
tags: []
user_id: lukaslange
