artifact_uri: ./mlruns/0/0bfee3c2c1ce4d759c3d095239d3f608/artifacts
end_time: 1649867197653
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 0bfee3c2c1ce4d759c3d095239d3f608
run_uuid: 0bfee3c2c1ce4d759c3d095239d3f608
source_name: ''
source_type: 4
source_version: ''
start_time: 1649867197620
status: 3
tags: []
user_id: lukaslange
