artifact_uri: ./mlruns/0/d2d1a5b07c784d048e5f12d2e8d0159a/artifacts
end_time: 1649937546274
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: d2d1a5b07c784d048e5f12d2e8d0159a
run_uuid: d2d1a5b07c784d048e5f12d2e8d0159a
source_name: ''
source_type: 4
source_version: ''
start_time: 1649937546203
status: 4
tags: []
user_id: lukaslange
