artifact_uri: ./mlruns/0/7e29af1d75ab44999c32d2b34875cede/artifacts
end_time: 1649862526111
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 7e29af1d75ab44999c32d2b34875cede
run_uuid: 7e29af1d75ab44999c32d2b34875cede
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862526063
status: 3
tags: []
user_id: lukaslange
