artifact_uri: ./mlruns/0/6f1db522752f48af889ba0c4d5eb93f1/artifacts
end_time: 1649865877571
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 6f1db522752f48af889ba0c4d5eb93f1
run_uuid: 6f1db522752f48af889ba0c4d5eb93f1
source_name: ''
source_type: 4
source_version: ''
start_time: 1649865877523
status: 3
tags: []
user_id: lukaslange
