artifact_uri: ./mlruns/0/0d65760be51d4d5cbbe9e50fe328e16d/artifacts
end_time: 1649862932340
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 0d65760be51d4d5cbbe9e50fe328e16d
run_uuid: 0d65760be51d4d5cbbe9e50fe328e16d
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862932316
status: 3
tags: []
user_id: lukaslange
