artifact_uri: ./mlruns/0/4ac934a11a7946fba6da91316fd187b6/artifacts
end_time: 1649938004345
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 4ac934a11a7946fba6da91316fd187b6
run_uuid: 4ac934a11a7946fba6da91316fd187b6
source_name: ''
source_type: 4
source_version: ''
start_time: 1649938003200
status: 3
tags: []
user_id: lukaslange
