artifact_uri: ./mlruns/0/aa33f845e9aa41658a349f960e9aa62c/artifacts
end_time: 1649862645736
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: aa33f845e9aa41658a349f960e9aa62c
run_uuid: aa33f845e9aa41658a349f960e9aa62c
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862645674
status: 3
tags: []
user_id: lukaslange
