artifact_uri: ./mlruns/0/31ae2b0a30744f26924d8c86d23d7adf/artifacts
end_time: 1649857971460
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 31ae2b0a30744f26924d8c86d23d7adf
run_uuid: 31ae2b0a30744f26924d8c86d23d7adf
source_name: ''
source_type: 4
source_version: ''
start_time: 1649857971421
status: 3
tags: []
user_id: lukaslange
