artifact_uri: ./mlruns/0/9daffb99ffee4b0cbdca4be233fcf79e/artifacts
end_time: 1649862932180
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 9daffb99ffee4b0cbdca4be233fcf79e
run_uuid: 9daffb99ffee4b0cbdca4be233fcf79e
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862932144
status: 3
tags: []
user_id: lukaslange
