artifact_uri: ./mlruns/0/84aeac1dd9cd4b66bbae8463168adbf3/artifacts
end_time: 1649862740666
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 84aeac1dd9cd4b66bbae8463168adbf3
run_uuid: 84aeac1dd9cd4b66bbae8463168adbf3
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862740638
status: 3
tags: []
user_id: lukaslange
