artifact_uri: ./mlruns/0/bdc1b333054540fd82e8fd89242ad50f/artifacts
end_time: 1649862932098
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: bdc1b333054540fd82e8fd89242ad50f
run_uuid: bdc1b333054540fd82e8fd89242ad50f
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862932058
status: 3
tags: []
user_id: lukaslange
