artifact_uri: ./mlruns/0/9fee01bfaef043a69a2b728cb8f24661/artifacts
end_time: 1649862932882
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 9fee01bfaef043a69a2b728cb8f24661
run_uuid: 9fee01bfaef043a69a2b728cb8f24661
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862932856
status: 3
tags: []
user_id: lukaslange
