artifact_uri: ./mlruns/0/de699e7bdb6c483c9468a725c7eb5443/artifacts
end_time: 1649865264243
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: de699e7bdb6c483c9468a725c7eb5443
run_uuid: de699e7bdb6c483c9468a725c7eb5443
source_name: ''
source_type: 4
source_version: ''
start_time: 1649865264212
status: 3
tags: []
user_id: lukaslange
