artifact_uri: ./mlruns/0/0ecf2efce8654b74a470f3285cefed8a/artifacts
end_time: 1649862741067
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 0ecf2efce8654b74a470f3285cefed8a
run_uuid: 0ecf2efce8654b74a470f3285cefed8a
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862741041
status: 3
tags: []
user_id: lukaslange
