artifact_uri: ./mlruns/0/67131c38a2f64fd9badd399d792afe5e/artifacts
end_time: 1649862932784
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 67131c38a2f64fd9badd399d792afe5e
run_uuid: 67131c38a2f64fd9badd399d792afe5e
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862932745
status: 3
tags: []
user_id: lukaslange
