artifact_uri: ./mlruns/0/ae354fa49f464eaab76a9e7dc54ad99c/artifacts
end_time: 1649862740598
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: ae354fa49f464eaab76a9e7dc54ad99c
run_uuid: ae354fa49f464eaab76a9e7dc54ad99c
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862740569
status: 3
tags: []
user_id: lukaslange
