artifact_uri: ./mlruns/0/179b83c228d342ef8dd296cdc7e5bcbd/artifacts
end_time: 1649862932817
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 179b83c228d342ef8dd296cdc7e5bcbd
run_uuid: 179b83c228d342ef8dd296cdc7e5bcbd
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862932787
status: 3
tags: []
user_id: lukaslange
