artifact_uri: ./mlruns/0/e5ad461e15f149828085b6bbebfc50da/artifacts
end_time: 1649862740761
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: e5ad461e15f149828085b6bbebfc50da
run_uuid: e5ad461e15f149828085b6bbebfc50da
source_name: ''
source_type: 4
source_version: ''
start_time: 1649862740734
status: 3
tags: []
user_id: lukaslange
