artifact_uri: ./mlruns/0/ac53b94aaad84d8895b0803aa52c74f6/artifacts
end_time: 1649867110608
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: ac53b94aaad84d8895b0803aa52c74f6
run_uuid: ac53b94aaad84d8895b0803aa52c74f6
source_name: ''
source_type: 4
source_version: ''
start_time: 1649867110553
status: 3
tags: []
user_id: lukaslange
