artifact_uri: ./mlruns/0/a26794e9942f42aaa6930ab6d7ab6d62/artifacts
end_time: 1649938286115
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: a26794e9942f42aaa6930ab6d7ab6d62
run_uuid: a26794e9942f42aaa6930ab6d7ab6d62
source_name: ''
source_type: 4
source_version: ''
start_time: 1649938279186
status: 4
tags: []
user_id: lukaslange
