artifact_uri: ./mlruns/0/9d0aca9e6eb14b46aba2b41536a3e1e5/artifacts
end_time: 1649865793910
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: deleted
name: ''
run_id: 9d0aca9e6eb14b46aba2b41536a3e1e5
run_uuid: 9d0aca9e6eb14b46aba2b41536a3e1e5
source_name: ''
source_type: 4
source_version: ''
start_time: 1649865793877
status: 3
tags: []
user_id: lukaslange
